In [4]:
#2
import pandas as pd

In [7]:
df= pd.read_csv("neet_data.csv")

In [8]:
df

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,44135.590602,141,Twitter for Android,1250294694937910000,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,44135.590405,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,44135.590139,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,44135.590058,141,Twitter for Android,1085818329816880000,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,44135.589838,0,Twitter for Android,1227501071490110000,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,44134.645544,0,Twitter for Android,1168840190426630000,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,44134.645544,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,44134.645127,167,Twitter for Android,1313330869113740000,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,44134.644873,270,Twitter for Android,1161551282995380000,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,44134.644606,0,Twitter for Android,1211810532006610000,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [9]:
df.columns

Index(['created_at', 'retweet_count', 'source', 'user_id', 'user_name',
       'user_description', 'user_follower_count', 'user_friends_count',
       'user_location', 'user_verified', 'user_url', 'tweet',
       'length_of_tweet'],
      dtype='str')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 47381 entries, 0 to 47380
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   created_at           47381 non-null  float64
 1   retweet_count        47381 non-null  int64
 2   source               47362 non-null  str
 3   user_id              47381 non-null  int64
 4   user_name            47380 non-null  str
 5   user_description     36510 non-null  str
 6   user_follower_count  47381 non-null  int64
 7   user_friends_count   47381 non-null  int64
 8   user_location        26247 non-null  str
 9   user_verified        47381 non-null  bool
 10  user_url             9280 non-null   str
 11  tweet                47381 non-null  str
 12  length_of_tweet      47381 non-null  int64
dtypes: bool(1), float64(1), int64(5), str(6)
memory usage: 4.4 MB

In [15]:
df.shape

(47381, 13)

In [6]:
#3
df.sort_values(by="retweet_count",ascending=False)

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
32860,44143.229178,614304,Twitter for iPhone,1024658968394620000,\xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3,\xe3\x85\xa4\xe3\x82\xa2\xe3\x82\xa4\xe3\x82\x...,62,115,NaN,False,https://t.co/cHZdP4uOdu,"RT @JoeBiden: America, I\xe2\x80\x99m honored ...",140
33262,44142.911736,581097,Twitter for Android,1099388669448860000,Neet\xf0\x9f\x83\x8fPeet,\xe2\x96\xa0\xe2\x96\xa0\xe2\x96\xa0\xe2\x96\x...,11,141,NaN,False,NaN,"RT @KamalaHarris: We did it, @JoeBiden. https:...",63
35111,44141.597604,381458,Twitter Web App,2578241503,\xe3\x81\xaf\xe3\x81\xaa\xe3\x81\x91\xe3\x81\x...,Kei|20\xe2\x86\x91|intp|eng/fil OK|SparQlew\xe...,624,527,read carrd before follow!!,False,https://t.co/XgmHbPUgAi,RT @GretaThunberg: So ridiculous. Donald must ...,140
32585,44143.304884,204348,Twitter for iPhone,1103362192169180000,Parneet kaur,"\xf0\x9f\x96\x95 all negative , all positive v...",587,193,"New Jersey, USA",False,https://t.co/PXgYJf0gIA,RT @Al_Sanchino: It\xe2\x80\x99s wild Trump su...,140
38044,44139.763345,192350,Twitter for iPhone,54249914,Couture_Neet,snapchat . Neetsobeautiful,547,1182,Miii Casaa,False,NaN,"RT @JoeBiden: Keep the faith, guys. We\xe2\x80...",57
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33534,44142.698368,0,Twitter Web App,1301196667887030000,\xe0\xae\xaa\xe0\xae\xbe\xe0\xae\x9c\xe0\xae\x...,"Indian,BJP supporter",11,37,Tirunelveli,False,NaN,@mosquitomani @vishnuuparam @onandi143 When Bj...,140
33533,44142.698750,0,Twitter for iPhone,2835488103,Praise be to Hibiki (Thanks be to Symphogear),Blessed be the name of Hibiki\nBuilt a new DnD...,1324,4252,Ha ha! Time for ethics!,False,NaN,@FallerHunter03 @icypika @ooo_thank @HerShinin...,140
13611,44131.057674,0,Twitter for Android,1207560622273150000,sochkpostkaro,Janta ki awaz uthayenge,24,164,NaN,False,NaN,@Imritik_ @Swamy39 @theicai Galat insan ko tag...,140
33531,44142.700116,0,Twitter for Android,905021614546313000,Indore Talk,Indore Talk is City's First Hyperlocal Infotai...,5031,25,"Indore, India",False,https://t.co/41cPZozsD8,#FeaturedTalk: Prepare with the Subject Expert...,140
47380,44134.644606,0,Twitter for Android,1211810532006610000,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [10]:
#4
df.sort_values(by="retweet_count",ascending=False)[
['source','retweet_count','user_name','tweet','created_at','user_url']
    ].head(1)

,source,retweet_count,user_name,tweet,created_at,user_url
32860,Twitter for iPhone,614304,\xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3,"RT @JoeBiden: America, I\xe2\x80\x99m honored ...",44143.229178,https://t.co/cHZdP4uOdu

In [15]:
#5
df['retweet_count'].nlargest(10).sum()

np.int64(2652225)

In [16]:
#6
android_df=df[df['source']=='Twitter for Android']
android_df.shape[0]
android_df['retweet_count'].sum()

np.int64(9386742)

In [21]:
#7
df.sort_values(by='user_follower_count',ascending=False).iloc[0][
['user_name','user_location']
    ]

user_name         NDTV
user_location    India
Name: 44355, dtype: object

In [12]:
#8
import pandas as pd
df= pd.read_csv("neet_data.csv")
df['followers_friend_ratio']=(
    df['user_follower_count']/
    df['user_friends_count']
)
df.head()

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet,followers_friend_ratio
0,44135.590602,141,Twitter for Android,1250294694937910000,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139,0.077778
1,44135.590405,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140,0.770819
2,44135.590139,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139,0.281343
3,44135.590058,141,Twitter for Android,1085818329816880000,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139,0.314775
4,44135.589838,0,Twitter for Android,1227501071490110000,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140,0.083333

In [13]:
#9
df.isnull().sum()

created_at                    0
retweet_count                 0
source                       19
user_id                       0
user_name                     1
user_description          10871
user_follower_count           0
user_friends_count            0
user_location             21134
user_verified                 0
user_url                  38101
tweet                         0
length_of_tweet               0
followers_friend_ratio      147
dtype: int64

In [12]:
#10
df['user_description'].fillna("twitter user",inplace=True)

C:\Users\verma\AppData\Local\Temp\ipykernel_14208\1876582430.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['user_description'].fillna("twitter user",inplace=True)

0                                             twitter user
1        Proud dad of three & cat, @SussexCCC fan. CEO ...
2        Wisdom is knowing the right path to take, Inte...
3                                             twitter user
4                       it's not my attitude it's my style
                               ...
47376                                       Bhola sa chora
47377    Random person who likes drawing (but not a \nl...
47378                                         twitter user
47379    Finding the enemies of India \xf0\x9f\x87\xae\...
47380    404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...
Name: user_description, Length: 47381, dtype: str

In [15]:
#11
df.dropna(axis=1, inplace=True)
df.columns

Index(['created_at', 'retweet_count', 'user_id', 'user_follower_count',
       'user_friends_count', 'user_verified', 'tweet', 'length_of_tweet'],
      dtype='str')

In [16]:
#12
df.insert(2,'is allow',True)
df.head

<bound method NDFrame.head of          created_at  retweet_count  is allow              user_id  \
0      44135.590602            141      True  1250294694937910000
1      44135.590405              1      True             57059492
2      44135.590139            141      True           1016022678
3      44135.590058            141      True  1085818329816880000
4      44135.589838              0      True  1227501071490110000
...             ...            ...       ...                  ...
47376  44134.645544              0      True  1168840190426630000
47377  44134.645544           1700      True           1696615807
47378  44134.645127            167      True  1313330869113740000
47379  44134.644873            270      True  1161551282995380000
47380  44134.644606              0      True  1211810532006610000

       user_follower_count  user_friends_count  user_verified  \
0                       14                 180          False
1                     2314                3002          False
2                      285                1013          False
3                      147                 467          False
4                        2                  24          False
...                    ...                 ...            ...
47376                  254                 513          False
47377                   23                 754          False
47378                    2                   2          False
47379                  140                1309          False
47380                   16                  45          False

                                                   tweet  length_of_tweet
0      RT @Kwa_Mamkhize: I am giving away R5K to 100 ...              139
1      \xf0\x9f\x91\x87This is a really important iss...              140
2      RT @Kwa_Mamkhize: I am giving away R5K to 100 ...              139
3      RT @Kwa_Mamkhize: I am giving away R5K to 100 ...              139
4      @RomeshSabharwal @ArvindKejriwal Romesh Sabhar...              140
...                                                  ...              ...
47376  Friend Request \xe2\x9d\x8c\nAcid request \xe2...               56
47377  RT @Telepeturtle: those are some pretty nice s...               74
47378  RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...              140
47379  RT @OpIndia_com: Yogi Adityanath asks chief se...              140
47380  i hate talking to people from my department bu...              139

[47381 rows x 9 columns]>

In [18]:
#13
df.drop(columns=['tweet'],inplace=True)
df.head

<bound method NDFrame.head of          created_at  retweet_count  is allow              user_id  \
0      44135.590602            141      True  1250294694937910000
1      44135.590405              1      True             57059492
2      44135.590139            141      True           1016022678
3      44135.590058            141      True  1085818329816880000
4      44135.589838              0      True  1227501071490110000
...             ...            ...       ...                  ...
47376  44134.645544              0      True  1168840190426630000
47377  44134.645544           1700      True           1696615807
47378  44134.645127            167      True  1313330869113740000
47379  44134.644873            270      True  1161551282995380000
47380  44134.644606              0      True  1211810532006610000

       user_follower_count  user_friends_count  user_verified  length_of_tweet
0                       14                 180          False              139
1                     2314                3002          False              140
2                      285                1013          False              139
3                      147                 467          False              139
4                        2                  24          False              140
...                    ...                 ...            ...              ...
47376                  254                 513          False               56
47377                   23                 754          False               74
47378                    2                   2          False              140
47379                  140                1309          False              140
47380                   16                  45          False              139

[47381 rows x 8 columns]>

In [29]:
#14
df['created_at'] = pd.to_datetime(df['created_at'])
df['month'] = df['created_at'].dt.month
df['year'] = df['created_at'].dt.year
df[['created_at','month','year']].head()

                     created_at  month  year
0 1970-01-01 00:00:00.000044135      1  1970
1 1970-01-01 00:00:00.000044135      1  1970
2 1970-01-01 00:00:00.000044135      1  1970
3 1970-01-01 00:00:00.000044135      1  1970
4 1970-01-01 00:00:00.000044135      1  1970